library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity VerticalSync is
	Port (
		HRESET  : in  STD_LOGIC;
		VSYNC   : out STD_LOGIC;
		VSYNCn  : out STD_LOGIC;
		V1      : out STD_LOGIC;
		V2      : out STD_LOGIC;
		V4      : out STD_LOGIC;
		V8      : out STD_LOGIC;
		V16     : out STD_LOGIC;
		V32     : out STD_LOGIC;
		V64     : out STD_LOGIC;
		V64n    : out STD_LOGIC;
		V128    : out STD_LOGIC;
		V128n   : out STD_LOGIC;
		V256    : out STD_LOGIC;
		V256n   : out STD_LOGIC;
		VRESET  : out STD_LOGIC;
		VRESETn : out STD_LOGIC
	);
end VerticalSync;

architecture Behavioral of VerticalSync is

-- Internal signals for outputs that are read back (VHDL-93 can't read out ports)
signal v1_i, v2_i, v4_i, v8_i    : STD_LOGIC;
signal v16_i, v32_i, v64_i       : STD_LOGIC;
signal v128_i, v256_i             : STD_LOGIC;
signal vreset_i, vresetn_i        : STD_LOGIC;
signal vsync_i, vsyncn_i          : STD_LOGIC;
signal B1_p6                      : STD_LOGIC;

begin

-- Drive entity outputs from internal signals
V1      <= v1_i;
V2      <= v2_i;
V4      <= v4_i;
V8      <= v8_i;
V16     <= v16_i;
V32     <= v32_i;
V64     <= v64_i;
V128    <= v128_i;
V256    <= v256_i;
VRESET  <= vreset_i;
VRESETn <= vresetn_i;
VSYNC   <= vsync_i;
VSYNCn  <= vsyncn_i;
-- V64n and V128n generated by inverter gates below

-- First counter (D1) - generates V1, V2, V4, V8
D1: entity work.LS93
	port map(
		P1_CP1n  => v1_i,
		P2_MR1   => vreset_i,
		P3_MR2   => vreset_i,
		P8_Q2    => v4_i,
		P9_Q1    => v2_i,
		P11_Q3   => v8_i,
		P12_Q0   => v1_i,
		P14_CP0n => HRESET
	);

-- Second counter (C1) - generates V16, V32, V64, V128
C1: entity work.LS93
	port map(
		P1_CP1n  => v16_i,
		P2_MR1   => vreset_i,
		P3_MR2   => vreset_i,
		P8_Q2    => v64_i,
		P9_Q1    => v32_i,
		P11_Q3   => v128_i,
		P12_Q0   => v16_i,
		P14_CP0n => v8_i
	);

-- Flip-flop (B2) - generates V256/V256n
B2: entity work.LS107
	port map(
		P5_Q2     => v256_i,
		P6_Q2n    => V256n,
		P8_J2     => '1',
		P9_CLK2   => v128_i,
		P10_CLR2n => vresetn_i,
		P11_K2    => '1'
	);

-- Inverter (C6) - generates V64n and V128n
C6: entity work.LS04
	port map(
		P8_Y4  => V64n,
		P9_A4  => v64_i,
		P10_Y5 => V128n,
		P11_A5 => v128_i
	);

-- NAND gate (B1) - detects vertical reset condition (V256, V32, V16, V8 all high)
B1: entity work.LS20
	port map(
		P1_A1 => v256_i,
		P2_B1 => v32_i,
		P4_C1 => v16_i,
		P5_D1 => v8_i,
		P6_Y1 => B1_p6
	);

-- Flip-flop (D2) - generates VRESET/VRESETn
D2: entity work.LS74
	port map(
		P8_Q2n 	  => vreset_i,
		P9_Q2 	  => vresetn_i,
		P10_SET2n => '1',
		P11_CLK2  => HRESET,
		P12_D2	  => B1_p6,
		P13_CLR2n => '1'
	);

-- NOR gate (F3) - generates VSYNC/VSYNCn
F3: entity work.LS02
    port map(
		P8_A3 	=> v8_i,
		P9_B3 	=> vsyncn_i,
		P10_Y3 	=> vsync_i,
		P11_A4	=> vsync_i,
		P12_B4 	=> vreset_i,
		P13_Y4	=> vsyncn_i
    );

end Behavioral;
